<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * tool/import/lang/en/vocabai_imagen.php
 *
 * @package    vocabai_imagen
 * @copyright  2023 Gordon BATESON
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 * @author     Gordon BATESON https://github.com/gbateson
 * @since      Moodle 3.11
 */

$string['aspectratio'] = 'Aspect ratio';
$string['aspectratio_help'] = 'The required ratio, specified as width:height, of the generated images.

Ratios of 4:3 and 16:9 produce images that are wider than they are tall, i.e. "landscape" images.

Similarly, ratios of 3:4 and 9:16 produce images that are taller than they are wide, i.e. "portrait" images.

Ratios 4:3 and 3:4 are "normal screen" ratios, while ratios 16:9 and 9:16 are "widescreen" ratios.';
$string['cannoteditkeys'] = 'You cannot edit these keys.';
$string['compressionquality'] = 'Quality';
$string['compressionquality_help'] = 'The level of compression if the output type is JPG. Accepted values are 0 through 100. The default value is 75.';
$string['confirmcopykey'] = 'Are you sure you want to copy this key?';
$string['confirmdeletekey'] = 'Are you sure you want to delete this key?';
$string['copycancelled'] = 'Copying of the key was cancelled.';
$string['copycompleted'] = 'The key was successfully copied.';
$string['copykey'] = 'Copy API key for Google Imagen';
$string['deletecancelled'] = 'Key deletion was cancelled.';
$string['deletecompleted'] = 'The key was successfully deleted.';
$string['deletekey'] = 'Delete API key for Google Imagen';
$string['dimensions'] = 'Image dimensions';
$string['dimensions_help'] = 'Specify the maximum width and/or height of the image when stored in Moodle. The image will be resized so that the width and height do not exceed the limits specified here. The width to height ratio of the original image will be maintained when it is resized.';
$string['editcancelled'] = 'Editing of the key was cancelled.';
$string['editcompleted'] = 'The modified key was successfully saved.';
$string['imagen'] = 'Google Imagen';
$string['imagenkey'] = 'Imagen key';
$string['imagenkey_help'] = 'The key required to access Google Imagen\'s API. This usually starts "sk-" followed by 48 random letters and numbers.';
$string['imagenmodel'] = 'Imagen model';
$string['imagenmodel_help'] = 'The Google Imagen model to be used e.g. imagen-3';
$string['imagenmodelid'] = 'Imagen tuned model';
$string['imagenmodelid_help'] = 'The Google Imagen model that has been tuned using this tuning file.';
$string['imagenurl'] = 'Imagen url';
$string['imagenurl_help'] = 'The URL of Google Imagen\'s API e.g. https://generativelanguage.googleapis.com/v1. The lastest release of a versiona may be available by appending "beta" to the URL.';
$string['keeporiginals'] = 'Keep original images';
$string['keeporiginals_help'] = '**No**
If the file type, quality or dimensions of the image are changed, then the original image will be deleted and only the converted images will kept.

**Yes**
The original high-resolution images from Google Imagen will always be kept.

The original files are typically about 2 ~ 3 MB in size, whereas the converted files are typically about 500 KB in size.';
$string['maxheight'] = 'Maximum height';
$string['maxheight_help'] = 'The maximum height (in pixels) of the image when stored in Moodle.';
$string['maxwidth'] = 'Maximum width';
$string['maxwidth_help'] = 'The maximum width (in pixels) of the image when stored in Moodle.';
$string['mimetype'] = 'Mime type from Imagen';
$string['mimetype_elements'] = 'Image type';
$string['mimetype_elements_help'] = 'These settings specify the mime type, also known as the file type, of the content generated by Google Imagen and stored in Moodle. Google Imagen models can generate PNG or JPG content, and these can be converted to other file types within Moodle.';
$string['mimetype_help'] = 'The Google Imagen models can generate PNG or JPG content, and these can be converted to other formats within Moodle.';
$string['mimetypeconvert'] = 'Mime type within Moodle.';
$string['mimetypeconvert_help'] = 'The mime type used when storing the generated images within Moodle.';
$string['mimetypefile'] = '{$a} file';
$string['nokeysfound'] = 'No keys found';
$string['note'] = 'Note';
$string['persongeneration'] = 'Allow people';
$string['persongeneration_allowadult'] = 'Images may contain adult people only';
$string['persongeneration_allowall'] = 'Images may contain people of all ages';
$string['persongeneration_default'] = 'Default (Images may contain adult people only)';
$string['persongeneration_dontallow'] = 'Images may not contain people or faces';
$string['persongeneration_help'] = 'Allow the generated images to contain depictions of people.';
$string['pluginname'] = 'Google Imagen AI assistant for a Vocabulary activity.';
$string['privacy:metadata'] = 'The vocabai_imagen plugin does not store any personal data.';
$string['ratiodescription'] = '{$a->ratio} ({$a->orientation}, {$a->size})';
$string['ratiolandscape'] = 'landscape';
$string['rationormal'] = 'normal';
$string['ratioportrait'] = 'portrait';
$string['ratiosquare'] = 'square';
$string['ratiowide'] = 'widescreen';
$string['samplecount'] = 'Number of images';
$string['samplecount_help'] = 'The number of sample images to generate. It must be between 1 and 4, and defaults to 2.

All variations will be converted to the required file type, quality and dimensions and stored within Moodle. The first image will be inserted into the question, but the others will remain accessible as "Embedded files".';
