<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * tool/import/lang/en/vocabai_dalle.php
 *
 * @package    vocabai_dalle
 * @copyright  2023 Gordon BATESON
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 * @author     Gordon BATESON https://github.com/gbateson
 * @since      Moodle 3.11
 */

$string['cannoteditkeys'] = 'You cannot edit these keys.';
$string['confirmcopykey'] = 'Are you sure you want to copy this key?';
$string['confirmdeletekey'] = 'Are you sure you want to delete this key?';
$string['copycancelled'] = 'Copying of the key was cancelled.';
$string['copycompleted'] = 'The key was successfully copied.';
$string['copykey'] = 'Copy API key for DALL-E';
$string['dall-e-2'] = 'Generates creative images quickly with good quality.';
$string['dall-e-3'] = 'Generates high-quality, detailed images with better prompt accuracy.';
$string['dalle'] = 'OpenAI DALL-E';
$string['dallekey'] = 'DALL-E key';
$string['dallekey_help'] = 'The key required to access OpenAI DALL-E\'s API. This usually starts "sk-" followed by 48 random letters and numbers.';
$string['dallemodel'] = 'DALL-E model';
$string['dallemodel_help'] = 'The OpenAI DALL-E model to be used e.g. dall-e-2, dall-e-3';
$string['dallemodelid'] = 'DALL-E tuned model';
$string['dallemodelid_help'] = 'The OpenAI DALL-E model that has been tuned using this tuning file.';
$string['dalleurl'] = 'DALL-E url';
$string['dalleurl_help'] = 'The URL of OpenAI DALL-E\'s API e.g. https://api.openai.com/v1/audio/speech';
$string['deletecancelled'] = 'Key deletion was cancelled.';
$string['deletecompleted'] = 'The key was successfully deleted.';
$string['deletekey'] = 'Delete API key for DALL-E';
$string['editcancelled'] = 'Editing of the key was cancelled.';
$string['editcompleted'] = 'The modified key was successfully saved.';
$string['filetype'] = 'File type from DALL-E';
$string['filetype_elements'] = 'Image file type';
$string['filetype_elements_help'] = 'These settings specify the file type, also known as th MIME type, of the content generated by OpenAI DALL-E and stored in Moodle. Although OpenAI DALL-E models only generate PNG content, this can be converted to other file types within Moodle.';
$string['filetype_help'] = 'The OpenAI DALL-E models only generate PNG content. However, this can be converted to other formats within Moodle.';
$string['filetypeconvert'] = 'File type within Moodle.';
$string['filetypeconvert_help'] = 'The file type used to store the images within Moodle.';
$string['filetypefile'] = '{$a} file';
$string['keeporiginals'] = 'Keep original images';
$string['keeporiginals_help'] = '**No**
If the file type, quality or dimensions of the image are changed, then the original image will be deleted and only the converted images will kept.

**Yes**
The original high-resolution images from OpenAI DALL-E will always be kept.

The original files are typically about 2 ~ 3 MB in size, whereas the converted files are typically about 500 KB in size.';
$string['n'] = 'Image count';
$string['n_help'] = 'The number of variations of the image to generate. It must be between 1 and 10, and defaults to 1.

All variations will be converted to the required file type, quality and dimensions and stored within Moodle. The first image will be inserted into the question, but the others will remain accessible as "Embedded files".';
$string['nokeysfound'] = 'No keys found';
$string['note'] = 'Note';
$string['pluginname'] = 'OpenAI DALL-E AI assistant for a Vocabulary activity.';
$string['privacy:metadata'] = 'The vocabai_dalle plugin does not store any personal data.';
$string['quality'] = 'Quality of images from DALL-E';
$string['quality_elements'] = 'Image quality';
$string['quality_elements_help'] = 'The settings specify quality of the images that are generated by OpenAI DALL-E and stored in Moodle.';
$string['quality_help'] = 'The quality of images generated by OpenAI DALL-E. A value of "High definition" creates images with finer details and greater consistency across the image. This param is only supported for OpenAI DALL-E-3.';
$string['qualityconvert'] = 'Quality of images in Moodle';
$string['qualityconvert_help'] = 'The quality of images when they are stored in Moodle. Specifying a high percentage will lead to greater definition in the stored images, but also larger file sizes.';
$string['qualityhd'] = 'High definition';
$string['qualitystandard'] = 'Standard definition';
$string['response_format'] = 'Image format';
$string['response_format_help'] = 'The format in which the generated images are returned. This must be either "url" or "b64_json". URLs are only valid for 60 minutes after the image has been generated.';
$string['response_formatb64_json'] = 'Base64 (json) format';
$string['response_formaturl'] = 'URL';
$string['size'] = 'Dimensions of images from DALL-E';
$string['size_elements'] = 'Image dimensions';
$string['size_elements_help'] = 'These settings specify the dimensions of the generated images. The images generated by OpenAI DALL-E are fairly large files (2~3 MB). Converting to smaller dimensions will reduce the file size.';
$string['size_help'] = 'The pixel dimensions (width x height) of images that are generated by OpenAI DALL-E. Only the dimensions listed here are available.

**DALL-E-2**
The size must be one of 256x256, 512x512, or 1024x1024.

**DALL-E-3**
The size must be one of 1024x1024, 1792x1024, or 1024x1792.';
$string['sizeconvert'] = 'Dimensions of images in Moodle';
$string['sizeconvert_help'] = 'The pixel dimensions (width x height) of the images when they are stored in Moodle. Reducing the image dimensions will reduce the size of the file stored in Moodle.';
$string['sizelandscape'] = '▬ {$a}: Landscape orientation';
$string['sizeportrait'] = '▮ {$a}: Portrait orientation';
$string['sizesquare'] = '■ {$a}: Square';
$string['style'] = 'Image style';
$string['style_help'] = 'The style of the generated images. Must be either "vivid" or "natural". Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images. This param is only supported for DALL-E-3.';
$string['stylenatural'] = 'Natural style';
$string['stylevivid'] = 'Vivid style';
